### ISSUE TITLE
Bad design of wait list

### ISSUE THREAD

**Issue by zonyitoo** [zonyitoo/coio-rs#19]
In `sync/mpsc.rs`

```rust
impl<T> Receiver<T> {
    pub fn recv(&self) -> Result<T, RecvError> {
        loop {
            // 1. Try receive
            match self.try_recv() {
                Ok(v) => return Ok(v),
                Err(TryRecvError::Empty) => {}
                Err(TryRecvError::Disconnected) => return Err(RecvError),
            }

            {
                // 2. Lock the wait list
                let mut wait_list = self.wait_list.lock().unwrap();

                // 3. Try to receive again, to ensure no one sent items into the queue while
                //    we are locking the wait list
                match self.try_recv() {
                    Ok(v) => return Ok(v),
                    Err(TryRecvError::Empty) => {}
                    Err(TryRecvError::Disconnected) => return Err(RecvError),
                }

                // 4. Push ourselves into the wait list
                wait_list.push_back(unsafe {
                    Processor::current().running().expect("A running coroutine is required!")
                });

                // 5. Release the wait list
            }

            // NOTE: WHAT IF the thread is switched right here?
            // Then the other thread may get the coroutine in the `wait_list`, and insert it by `Processor::ready`
            // and wake it up while it is still not blocked.
            // CRASH!

            // 6. Yield
            Scheduler::block();
        }
    }
}
```

**Comment by zonyitoo** [comment]
Reopen for comments

**Comment by lhecker** [comment]
*I'm sorry if the following sounds a bit amateurish:*

I'd really like to help but I fear that I didn't fully grasp the entire logic in coio within the past hours... So please let me ask a question first, in the context of the `wait_list` problem above:

* Is it correct that calling `Processor::ready()` (by `Sender::send()`) cannot directly (i.e. recursively) run an already active coroutine (the one running the loop in `Receiver::recv()`) within the same thread? I'm assuming it since it only pushes the targeted coroutine in the queue, which get's processed by `Processor::schedule()`, which in turn should already be busy with the current coroutine...
* Is it correct that yielding to `main_coro` in `Processor` basically continues the loop in `Processor::schedule()`? (This is the hardest question for me currently...)
* So... basically it won't "crash" right away, since nothing else happens besides 2 threads executing the same coroutine at the same time...?

I believe there is not a lot you could do about the `wait_list` since the list is kinda essential and can't really be removed and the list has to be filled before blocking the current coroutine, which in turn "blocks" and thus you can't extend the reach of `wait_list`s LockGuard to include the call to `Scheduler::block()`... Even Go uses 2 wait queues: https://github.com/golang/go/blob/67faca7d9c54b367aee5fdeef2d5dd609fcf99d0/src/runtime/chan.go#L34
I also think that some kind of lock for `Coroutine` instances is essential, since even the context swap must be protected. I do not believe that there is a solution that uses simple atomics except if you're fine with busy waiting.

But I do think that you could improve the locking part by inverting your current logic!

Just go from
> Resuming a coroutine locks the `yield_lock` (thus maintaining a lock all the time).

to
> The `yield_lock` can manually be acquired before the context swap, and can be released by `block_unlock()` which in turn unlocks it **in the new context** (thus after the swap is definitely over). If you do not lock `yield_lock`, call `block()` which does not bother with unlocking.

Thus you could make locking optional (As far as I understand the code it should be possible?) and definitely reduce the time the lock is held. You just need to use a Semaphore instead of Mutex...

**Comment by zonyitoo** [comment]
1. `Processor::ready` is just going to push it into the current thread's work queue, and it **may** be the next one to be ran in the current thread, or it will be *steal* by a starved thread.

2. `main_coro` is just for storing the CPU registers for the *current thread*. And yes, you are right.

3. Actually things will happen when the **current coroutine** (A) has been pushed into the `wait_list`, and then the current thread release the lock. But right now, a thread gets the lock of the `wait_list`, and takes out the (A) from the `wait_list`, and then pushed it into the work queue and try to wake (A) up. But right now, the `Scheduler::block()` haven't been finished yet, so the registers' value is still invalid. When it is waked up, memory gets ruined.

I have read some of the code in Go's runtime, but I don't know all the detail of their implementation. So it is welcome to improve the current MPSC implementation.

**Comment by lhecker** [comment]
Ah thanks to you explaination a light dawned on me and I think I understand how Processor works now. :blush: 
But as I said I don't think the current MPSC classes can generally be improved (except for minor optimizations which can be added later) to cover the call to `Scheduler::block()` with a lock (since the execution ends there!). But I do think you can fix the Coroutine/Processor by making it release a lock for you after the context switch happened...

Surprisingly that's even the way Go does it: https://github.com/golang/go/blob/67faca7d9c54b367aee5fdeef2d5dd609fcf99d0/src/runtime/chan.go#L163-L213

Go uses `lock()` at the beginning, enqueues the coroutine reference in L212 and then parks and unlocks the current coroutine (using semaphores): https://github.com/golang/go/blob/f90b48e0d347077cee4b6ea81671bfa04ddf681b/src/runtime/proc.go#L245-L266
They don't seem to swap the context though (which should improve performance a bit). I guess their scheduler is run in a seperate thread huh?

But I don't think it makes a difference... We just need a way to pass the reference to a semaphore from one context to the next one which can do the dirty work of unlocking for us.

**Comment by zonyitoo** [comment]
Their scheduler actually is running in a single Goroutine (Coroutine), and the context of the scheduler is stored in a global variable. Every time a coroutine yield, it will yield which that var.

In coio, the `Scheduler` actually acts like an I/O thread, which controls the `EventLoop`. The `Processor` acts more like a scheduler.

**Comment by lhecker** [comment]
Yep I think I understood the distinction between Scheduler/Processor/Coroutine...
But is my proposal of introducing a `Processor::block_and_unlock()` using semaphores feasible? And if so: Is it any better than your current more generic approach in the `Processor::resume()` method?

I studied the Go code a bit more and the way the channel works is basically (for e.g. sending - "translated" to the names used in coio):

----
Channel:
* Lock a Mutex `lock` on the channel (We don't need this since Rust's channel is thread safe)
* If "try_recv" is successful unlock `lock` and return (see first point)
* Add a reference to the current coroutine in to a "waiting" field on the Processor (AFAIK this is mainly for their `select()` implementation)
* Enqueue a reference to the coroutine in a send-waiting-list for the channel
* Call `goparkunlock()` with the currently held `lock`

----
→ Go Runtime
* Check and set states on the Processor and current Coroutine - also stores a (weak) reference to the lock which was passed (the `lock` above). (`acquirem()` and `releasem()` use ref-counting to lock the "Processor" (called *M*achine in Go) but I don't think that matters here)
* **Important part**: Calls `mcall(park_m)` which switches the current context with the scheduler's context (e.g. `main_coro`) and (*after* the switch) calls the passed callback (here: `park_m`)
* `park_m` *now* sets the Coroutine state back from running to waiting, disconnects it's dependency to the current Processor and *optionally* calls the unlock function for the stored reference to the lock.

This is basically nearly what I had in mind: Allocating a Lock on the stack or with some object (e.g. `Sender`/`Receiver`) or sth., pass it as a optional reference (a nullable pointer?) to the park/block method, which in turn unlocks it after the context switch (if it was passed). :blush: 

What do you think about this? Is it any better then your workaround?

**Comment by zonyitoo** [comment]
I think I have got your basic idea. That looks great!

> (after the switch) calls the passed callback

This is the most important part. :P

**Comment by lhecker** [comment]
Hey @zonyitoo I noticed that you pushed some code regarding this issue... Do you want to continue working on this for now or should I send you a PR?

**Comment by zonyitoo** [comment]
Nope, I just done something related to #16 . You are free to open a PR for this issue.

And the commit that referenced this issue is just to for replacing the `Mutex` with `Semaphore`.

**Comment by lhecker** [comment]
FYI: The `Semaphore` does not compile on Windows. :disappointed: 

```
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: linking with `gcc` failed: exit code: 1
note: "gcc" [list of parameters]
note: C:\...\target\debug\deps\libsema-95c293f55ddb47e3.rlib(sema-95c293f55ddb47e3.0.o): In function `sema::sys::os::Semaphore::new':
C:\Users\...\.cargo\registry\src\github.com-88ac128001ac3a9a\sema-0.1.4\src/sys.rs:303: undefined reference to `sem_init'
C:\...\target\debug\deps\libsema-95c293f55ddb47e3.rlib(sema-95c293f55ddb47e3.0.o): In function `sema::sys::os::Semaphore::wait':
C:\Users\...\.cargo\registry\src\github.com-88ac128001ac3a9a\sema-0.1.4\src/sys.rs:314: undefined reference to `sem_wait'
C:\...\target\debug\deps\libsema-95c293f55ddb47e3.rlib(sema-95c293f55ddb47e3.0.o): In function `sema::sys::os::Semaphore::try_wait':
C:\Users\...\.cargo\registry\src\github.com-88ac128001ac3a9a\sema-0.1.4\src/sys.rs:325: undefined reference to `sem_trywait'
C:\...\target\debug\deps\libsema-95c293f55ddb47e3.rlib(sema-95c293f55ddb47e3.0.o): In function `sema::sys::os::Semaphore::wait_timeout':
C:\Users\...\.cargo\registry\src\github.com-88ac128001ac3a9a\sema-0.1.4\src/sys.rs:337: undefined reference to `sem_timedwait'
C:\...\target\debug\deps\libsema-95c293f55ddb47e3.rlib(sema-95c293f55ddb47e3.0.o): In function `sema::sys::os::Semaphore::post':
C:\Users\...\.cargo\registry\src\github.com-88ac128001ac3a9a\sema-0.1.4\src/sys.rs:348: undefined reference to `sem_post'
C:\...\target\debug\deps\libsema-95c293f55ddb47e3.rlib(sema-95c293f55ddb47e3.0.o): In function `sema::sys::os::Semaphore.Drop::drop':
C:\Users\...\.cargo\registry\src\github.com-88ac128001ac3a9a\sema-0.1.4\src/sys.rs:367: undefined reference to `sem_destroy'
```

**Comment by zonyitoo** [comment]
That sucks. I think you could open an issue in `sema` and ask him to fix this bug.

**Comment by zonyitoo** [comment]
Reverted, please check the latest commit.

**Comment by lhecker** [comment]
@zonyitoo For this proposal it would be necessary to store a closure in the Processor instance for the duration of the context swap right? Do you have an idea how to store such a closure? I tried to store a raw (fat) pointer to it but I fail to find a solution that let's me circumvent Rust's lifetime checks...

I've added this member to `Processor`:
```rust
block_fn: Option<*const Fn()>,
```

and this method:
```rust
pub fn block_fn(&mut self, f: &Fn()) {
    match self.cur_running.take() {
        None => {}
        Some(coro_ptr) => unsafe {
            self.set_last_result(Ok(State::Blocked));
            self.block_fn = Some(f); // <--- FAILS HERE
            (&mut *coro_ptr).yield_to(&*self.main_coro);
        },
    }

    if self.is_exiting {
        panic!(ForceUnwind);
    }
}
```

It obviously doesn't work though since `self` is `'static` and thus:
> expected `core::option::Option<*const core::ops::Fn() + 'static>`, found `core::option::Option<*const core::ops::Fn()>`

I've tried to do explicit casts but that doesn't work. Do you have an idea how this could be solved? I wouldn't consider copying the closure a "good" solution as this would result in a heap allocation...

**Comment by lhecker** [comment]
I finally discovered `mem::transmute` which makes it possible to circumvent this. :neutral_face:
I'm kinda sad that there is no middle ground for this which let's me drop lifetime specifiers without dropping everything else too...

**Comment by lhecker** [comment]
So I definitely figured out how to store a reference to a FnMut and invoke it after the switch, but the problem now is that calling `drop()` on a mutable reference to the LockGuard in the MPSC recv() and send() methods does seem to drop the LockGuard (and thus release the mutex)...

I "always" thought that Rust's mutable references do not carry the Copy trait, which would mean that the value is moved into the `drop()` method but that doesn't seem to be the case anymore... or did I do something wrong?

```rust
let mut wait_list = self.wait_list.lock().unwrap();

Scheduler::block_with(&mut || {
    // A
    drop(&mut wait_list);
    // B
});

// C
```

A and B will be reached but C won't. If I drop the mutex before the `block()` instead it works. Any ideas, @zonyitoo?

**Comment by zonyitoo** [comment]
For your use case, the closure actually does need to be stored into the `Processor`, you can just pass it through a Pointer. If you want to let the type checker do his job, maybe you can take a look at the [here](https://github.com/zonyitoo/coio-rs/blob/master/src/scheduler.rs#L412), and also, you can take a look at any Rust projects that has implemented `scoped-*` features, such as `scoped-threadpool`.

If you want to `drop` the `MutexGuard` inside `A` and `B`, why not try to move it into the closure.

```rust
let wait_list = self.wait_list.lock().unwrap();

Scheduler::block_with(&mut || {
    // A
    let mut move_in = wait_list; // Move it here, and then it will be destroyed after B
    // B
});

// C
```

The `drop` function is not the `delete` in C++. They are not the same thing.

**Comment by lhecker** [comment]
BTW: The `block_with()` method must either be a generic method `block_with<F>(f: F)` and put `f` into a `FnBox` (to make it `Size`d, or otherwise it can't be stored in the `Processor` struct), or I have to use a reference to a `Fn*` trait (since references are also `Size`d).

And `FnOnce` does not work for this AFAIK, because, as I said, FnOnce's interface is
```rust
extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
```
which means that I have to copy `self` to the stack, which doesn't work anymore if I use a reference to  `Fn*`, which is type erased and thus does not include the original type `F` anymore (and thus is unsized). If I don't use references I have to use a `FnBox` which would move the value to the heap and I think that would be kinda bad...

Or did I get sth. wrong? It would be really cool if there would be a way to do type erasure for `move || {}`-closures without requiring them to be moved on the first invocation...

**Comment by zonyitoo** [comment]
Theoretically, coroutine context switch should act just like function calls, so I think it is reasonable to make `block_with` has the following prototype:

```rust
fn block_with<'scope, F: FnMut() -> R + 'scope, R: 'scope>(&self, f: F) { ... }
```

**Comment by zonyitoo** [comment]
May already been solved in the latest commits. Closing.
