### ISSUE TITLE
Destruction of blocked coroutines is flawed

### ISSUE THREAD

**Issue by lhecker** [zonyitoo/coio-rs#23]
Currently if a Processor receives the Shutdown message it will destroy all coroutines by using panic!().
But not all Coroutines will be destroyed... Some of them are in the Blocked state and taken out of the Processor and are waiting in the mio EventLoop. Currently this still works okay-ish and destroys all the coroutines almost always.
But what happens if a coroutine is still stuck inside a IoHandlerMessage which in turn is still inside mio's queue? Those coroutines won't be destroyed...

I only see 2 options here:
* Simplify mio <> coio interaction and make it possible to destroy coroutines at all times. This would mean that we need to make sure that for instance mio's queue is completely empty.
* Use Arc<Coroutine> instead of Box<Coroutine> and instead of completely removing Coroutines from a Processor we would just give out a Arc reference. Thus a Processor would always know which Coroutines it owns.

I would personally prefer the first approach but I fear that it might lead to ugly code if we have to make always sure that coroutines are not stuck in some queue etc.

**Comment by lhecker** [comment]
I think this would solve this: https://github.com/zonyitoo/coio-rs/commit/6cab070ba241b4501090392ac835093126b27215#commitcomment-15343039

I'm not sure how this would work though, @zonyitoo, so either you have to explain it a bit more for me, or - if you can - please implement it. :)
I think it's "kinda" urgent because I definitely broke it with my changes a bit, but I'm not exactly sure why my code is not working as it was before...

**Comment by zonyitoo** [comment]
I don't think this would happens. Because

1. As you can see in `Scheduler::run`, the `loop` first run the `EventLoop::run_once` method to wakeup those blocked coroutines.

2. If the `main` coroutine exited (panicked or finished), it will trigger the code below `EventLoop::run_once`, which is sending the `Shutdown` message to all its workers.

3. In this case, the `EventLoop` is not running, so no blocked coroutine would be waken up by the `EventLoop`.

So I don't think this is an issue. Am I right?

**Comment by lhecker** [comment]
The problem is that we should treat mio as a "black box" because it's internals can change and I don't think that it would be a good idea to rely on some "undefined behaviour" by mio...
It's not even guarantued that all messages are processed in a single tick! Because of this: http://rustdoc.s3-website-us-east-1.amazonaws.com/mio/v0.5.x/mio/struct.EventLoopConfig.html#method.messages_per_tick
The default notify_capacity is 4096 and the messages_per_tick only 512, which means that it could very well be the case that there are some unprocessed messages...
I think some kind of "automatic" cleanup would be nice (i.e. by extending Coroutine's Drop trait to also unwind the stack)

**Comment by zonyitoo** [comment]
Indeed, that's what I suggested to do. Unwind the `Coroutine` while it is dropping.

**BUT**, if the `drop` is triggered while the thread is panicking, then the whole program will be killed by panicked while panicking.

**Comment by zonyitoo** [comment]
This may be fixed in the latest commit. Closing.

**Comment by zonyitoo** [comment]
I finally find the reason why the `block_with` function will crash sometimes. Because:

```rust
let mut r = None;

        {
            let mut cb = |p: &mut Processor, coro: Handle| {
                r = Some(f.take().unwrap()(p, coro));
            };
```

This piece of code is taken from the `block_with` function. What would happen if you drop the `coro` inside the callback function?! the `r` is created on the stack of `coro`, so if you drop the `coro` inside the function, the `r` is destroyed together!!!!!! So the `r = Some(f.take().unwrap()(p, coro));` accesses an invalid memory address!

**Comment by zonyitoo** [comment]
The only solution is to change the callback function from `FnOnce(&mut Processor, Handle) -> U` to `FnOnce(&mut Processor)`.

**Comment by lhecker** [comment]
I believe the only reason I made it possible for `block_with` to return a custom value was because I was struggling to circumvent Rust's borrow checker here: https://github.com/zonyitoo/coio-rs/blob/257d03700cb507fdf2edc3027971f6c56a403986/src/sync/mpsc.rs#L195

Today I know that we could also rewrite it by using some kind of unsafe logic. I'd still ask you, @zonyitoo, to solve this please.

**Comment by zonyitoo** [comment]
Already solved in the lastest commit in `feature-migrate_context1.0` branch.
