### ISSUE TITLE
API: blocking scheduler

### ISSUE THREAD

**Issue by 3Hren** [zonyitoo/coio-rs#4]
It would be great if `Scheduler` can be used in a blocking way providing `run(0)` method, which spawns no threads, but blocks the current thread until no asynchronous operations left (or no child coroutines left).

It allows to control worker threads more precisely. Currently we have at least one thread sleeping in `run(N)` method on `join`.

Moreover it means that all scheduling work will be performed in a single thread and no synchronization between cores required (as like as stealing feature).

It may be hard to implement, because currently all `Fn*` callbacks are bound to be `'static`.

**Comment by 3Hren** [comment]
I mean, work stealing feature is great, but its support consumes too much cycles for synchronization when they are not required.

For example, `boost::asio::io_service` works better using `io_service` per thread strategy rather than single `io_service` shared for all threads.

**Comment by zonyitoo** [comment]
Ah ha. Looks reasonable.

Actually there is a project called [mioco](https://github.com/dpc/mioco) have already implemented a single threaded coroutine scheduler. I also did some research on how to implement coroutines without any synchronization mechanisms, but failed because of there is had to find a way to bypass Rust's borrow checker.

I have tried to implement `asymmetric` and `symmetric` coroutines just like `Boost.Coroutines` in Rust. The `asymmetric` one is easy to implement, but the `symmetric` is not, because I cannot find a safe way to expose coroutine switch APIs.

The coroutine in `Boost.Asio` is one kind of stackless coroutines, and it is `asymmetric`. If you run multiple `io_services` per thread, synchronization is also required if you access to some shared data.

A single thread scheduler with no-synchronization between cores looks good, but it will be unsafe to access shared data. How could you tell the rustc that which of your coroutines are running in the same thread? Hm..

I also have a experimental project [eventedco](https://github.com/zonyitoo/eventedco). I don't know if it is still able to build with the latest compiler.

**Comment by zonyitoo** [comment]
In Rust, it is impossible to make this work, because it is not possible to let the compiler know whether you are running in single-thread mode or multi-threads mode, which will lead to completely different restriction on the coroutine's callback function.

So I think this feature won't be supported in the near future.
