### ISSUE TITLE
Stack unwinding error when dropping Handle in block_with

### ISSUE THREAD

**Issue by zonyitoo** [zonyitoo/coio-rs#44]
Run the unit test with

```
cargo test --release coroutine_unwinds_on_drop
```

You may saw the similar output:

```
     Running target/release/coio-d04fbdaaf3d53238

running 1 test
test coroutine::test::coroutine_unwinds_on_drop ... FAILED

failures:

---- coroutine::test::coroutine_unwinds_on_drop stdout ----
	thread 'coroutine::test::coroutine_unwinds_on_drop' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `1`)', src/coroutine.rs:336
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    coroutine::test::coroutine_unwinds_on_drop

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

But if you do **one of** the following modification

* Add `#[inline(never)]` on `coroutine::Coroutine::yield_with`
* Add `#[inline(never)]` on `processor::ProcessorHandle::block_with`

The problem will be solved magically!!

**Comment by lhecker** [comment]
It might be Boost.Context here which does not work as intended with Rust, because Rust's ABI is a bit different to to the "native" extern-C-ABI (which Boost.Context expects to be the case).
Maybe some Registers are not correctly preserved? Or maybe Boost.Context expects to be able to `pop` some stack value (like the return address of the current method)? And so on...

It might thus be necessary to painfully step through the code instruction by instruction to discover some accidentially trashed Register or something...

If my assumption above is correct it _might_ (again) be necessary to remove the `#[inline(always)]` from the context wrapper methods. That in turn would lead to a extremely high 500% performance overhead though (for x86_64 in this case).

**Comment by zonyitoo** [comment]
Maybe it could not be solved gracefully. So, just mark the `block_with` (now it is called `park_with`) that do not allow to drop the handle inside the callback function.
