### ISSUE TITLE
UdpSocket hangs on Readable event

### ISSUE THREAD

**Issue by zonyitoo** [zonyitoo/coio-rs#47]
The bug was only found on Windows. [This test](https://github.com/zonyitoo/coio-rs/blob/master/tests/echo.rs#L49) hangs forever.

Related issue: https://github.com/carllerche/mio/issues/378

**Comment by zonyitoo** [comment]
Fixed mysteriously. Don't know why.

**Comment by lhecker** [comment]
> Fixed mysteriously. Don't know why.

Every developer. Ever. But nice work - whoever it was! :joy:

**Comment by zonyitoo** [comment]
No. It is not working at ALL! According to the lastest AppVeyor's build!

**Comment by glasswings** [comment]
I missed those network tests at first because they compile into their own executable.

I'm on 64-bit MSYS2 / Win10, so maybe in a good place to track this down.  

Bisection notes, for later or anyone else:

2015-Dec-13 e63031c "add network tests" -- compiler error (current nightly)

2016-Feb-13 ed2754d "[#40] Migrate to context-rs v1.0" -- tests complete and fail

2016-Mar-18 774d3f4 "v0.2.0: Significantly improved IoHandler" -- tests hang

**Comment by zonyitoo** [comment]
Hmm, in 2015, or before we actually finished migrating our code from "one loop per thread" to one single IO thread, all tests on Windows are expected to fail, because IOCP doesn't support moving socket from one loop to another.

The problem is: in the UDP echo test, the event loop won't produce any events even if you're sure that you have already sent something to that socket.

**Comment by zonyitoo** [comment]
That PR cannot solve this issue. Reopen.

**Comment by zonyitoo** [comment]
Disable AppVeyor build until we solve this issue.

**Comment by zonyitoo** [comment]
Solved after migrated to MIO v0.6, still don't know why.
